---
smb_username: jellyfin
smb_password: "{{ vault_smb_jellyfin_password }}"
smb_mounts:
  - network_path: //DS216j/Videos
    local_path: /mnt/jellyfin
    options: '_netdev,dir_mode=0555,file_mode=0444'
  - network_path: //DS216j/ServerBackup/jellyfin
    local_path: "{{ smb_backup_folder }}"
    options: '_netdev,dir_mode=0555,file_mode=0444'

jellyfin_pkcs_output_path: '/var/lib/jellyfin/tls_certificate.p12'
jellyfin_pkcs_password: "{{ vault_jellyfin_pkcs_password }}"

certbot_deploy_hook: |
  #!/usr/bin/env bash

  OUTPUT_FILE={{ jellyfin_pkcs_output_path }}
  CERT_ENCKEY={{ jellyfin_pkcs_password }}

  openssl pkcs12 -export \
                  -out "$OUTPUT_FILE" \
                  -inkey "$RENEWED_LINEAGE/privkey.pem" \
                  -in "$RENEWED_LINEAGE/fullchain.pem" \
                  -name "$RENEWED_LINEAGE" \
                  -passout "pass:$CERT_ENCKEY"

  systemctl restart jellyfin
