---
jellyfin_media_dir: /mnt/jellyfin

smb_mounts:
  backup:
    network_path: //harkonnen.{{ local_domain }}/ServerBackup/jellyfin
    local_path: "{{ smb_backup_dir }}"
    options: '_netdev,dir_mode=0555,file_mode=0444'
    username: "{{ vault_smb_jellyfin_credentials.username }}"
    password: "{{ vault_smb_jellyfin_credentials.password }}"
  media:
    network_path: //harkonnen.{{ local_domain }}/Media
    local_path: "{{ jellyfin_media_dir }}"
    options: '_netdev,dir_mode=0555,file_mode=0444'
    username: "{{ vault_smb_jellyfin_credentials.username }}"
    password: "{{ vault_smb_jellyfin_credentials.password }}"
