---
pihole_webpassword: "{{ vault_pihole_webpassword }}"
pihole_gateway_address: "{{ gateway_address }}"
pihole_domain: "{{ local_domain }}"
pihole_upstream_dns:
  - "{{ hosts.unbound.ipv4_address }}"
  - "{{ ansible_default_ipv4.address }}#5353"  # local stubby instance
pihole_dnssec: 'false'
pihole_dnsmasq_conditional_fwd: 'true'
pihole_dnsmasq_conditional_fwd_rules:
  - server_ip: "{{ dhcp_address }}"
    network: "{{ dhcp_address }}/{{ ansible_default_ipv4.netmask }}"
    domain: "{{ pihole_domain }}"

pihole_ignore_localhost: 'yes'
pihole_maxdbdays: 2

pihole_adlists:
  - "{{ query('file', 'default_adlists.txt') }}"
  - "{{ query('file', 'pihole_adlists.txt') }}"
  - "{{ query('url', 'https://v.firebog.net/hosts/lists.php?type=tick') }}"
pihole_regexlists:
  - "{{ query('file', 'pihole_regexlist.txt') }}"
  - "{{ query('url', 'https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list') }}"
pihole_blacklists:
  - "{{ query('file', 'pihole_blacklist.txt') }}"
  - "{{ query('file', 'hpHosts_exp.txt') }}"
  - "{{ query('file', 'hpHosts_grm.txt') }}"
  - "{{ query('file', 'hpHosts_mmt.txt') }}"
pihole_whitelists:
  - "{{ query('file', 'pihole_whitelist.txt') }}"

pihole_dnsmasq_custom: |
  # --strict-order uses reverse order in dnsmasq conf files (see http://lists.thekelleys.org.uk/pipermail/dnsmasq-discuss/2015q3/009816.html)
  strict-order
  min-cache-ttl=2
  max-cache-ttl=86400

certbot_deploy_hook: |
  #!/usr/bin/env bash

  cat "$RENEWED_LINEAGE/privkey.pem" "$RENEWED_LINEAGE/cert.pem" > "$RENEWED_LINEAGE/lighttpd_combined.pem"
  systemctl restart lighttpd
