---
smb_username: plex
smb_password: "{{ vault_smb_plex_password }}"
smb_mounts:
  - network_path: //DS216j/Videos
    local_path: /mnt/plex
    options: '_netdev,dir_mode=0555,file_mode=0444'
  - network_path: //DS216j/ServerBackup/plex
    local_path: "{{ smb_backup_folder }}"
    options: '_netdev,dir_mode=0555,file_mode=0444'

plex_pkcs_output_path: '/var/lib/plexmediaserver/keystore.p12'
plex_pkcs_password: "{{ vault_plex_pkcs_password }}"

certbot_deploy_hook: |
  #!/usr/bin/env bash

  OUTPUT_FILE={{ plex_pkcs_output_path }}
  CERT_ENCKEY={{ plex_pkcs_password }}

  openssl pkcs12 -export \
                  -out "$OUTPUT_FILE" \
                  -inkey "$RENEWED_LINEAGE/privkey.pem" \
                  -in "$RENEWED_LINEAGE/fullchain.pem" \
                  -name "$RENEWED_LINEAGE" \
                  -passout "pass:$CERT_ENCKEY"

  systemctl restart plexmediaserver
