---
unbound_force_build: true
unbound_config: |
  server:
      # Use DNSSEC validation. Do not send EDNS client subnet information.
      module-config: "validator iterator"

      # A port number can be specified with @port (without spaces between interface and port number),
      # if not specified the default port (from port option) is used.
      interface: 0.0.0.0@53

      access-control: 10.0.0.0/8 allow
      access-control: 172.16.0.0/12 allow
      access-control: 192.168.0.0/16 allow
      access-control: fd00::/8 allow

      # Any occurrence of such addresses are removed from DNS answers. Additionally, the DNSSEC
      # validator may mark the answers bogus. This protects against so-called DNS Rebinding.
      private-address: 10.0.0.0/8
      private-address: 172.16.0.0/12
      private-address: 192.168.0.0/16
      private-address: 169.254.0.0/16
      private-address: fd00::/8
      private-address: fe80::/10

      # Hardening
      hide-identity: yes
      hide-version: yes
      hide-trustanchor: yes
      harden-algo-downgrade: yes
      # deny queries of type ANY with an empty response
      deny-any: yes

      # DNSSEC trust anchor
      #auto-trust-anchor-file: {{ unbound_conf_dir }}/root.key
      #root-hints: {{ unbound_root_hints_file }}

      # Required for TLS upstream forwarding
      # Requires unbound v1.7.0+
      tls-cert-bundle: /etc/ssl/certs/ca-certificates.crt

      # Message cache elements are prefetched before they expire to keep the cache up to date.
      # Turning it on gives about 10 percent more traffic and load on the machine,
      # but popular items do not expire from the cache.
      prefetch: yes
      # Fetch the DNSKEYs earlier in the validation process, when a DS record is encountered.
      # This lowers the latency of requests, but uses more CPU. If the cache is set to 0, it is no use.
      prefetch-key: yes

      # Performance optimisation
      # https://nlnetlabs.nl/documentation/unbound/howto-optimise/

      # use all CPUs
      num-threads: 1
      # power of 2 close to num-threads
      msg-cache-slabs: 2
      rrset-cache-slabs: 2
      infra-cache-slabs: 2
      key-cache-slabs: 2

      # more cache memory, rrset=msg*2
      rrset-cache-size: 50m
      msg-cache-size: 25m

      # Set the outgoing-range to as large a value as possible
      # Number of ports to open. This number of file descriptors can be opened per thread.
      outgoing-range: 2048

      # The num-queries-per-thread is best set at half the number of the outgoing-range,
      # but you would like a whole lot to be able to soak up a spike in queries.
      num-queries-per-thread: 1024

      # Larger socket buffer. OS may need config.
      # Default is 0 (use system value). On Fedora 30 / Ubuntu 18 the default appears to be 208 KiB.
      # The OS caps it at a maximum; on Linux, Unbound needs root permission to bypass the limit,
      # or the admin can use sysctl net.core.rmem_max / net.core.wmem_max.
      # Set sysctl net.core.wmem_max and sysctl net.core.rmem_max = 4194304 (4 MiB)
      so-rcvbuf: 4m
      so-sndbuf: 4m

      # Faster UDP with multithreading (only on Linux).
      so-reuseport: yes

      # Number of TCP buffers to allocate per thread. Default is 10.
      # For larger installations increasing this value is a good idea.
      outgoing-num-tcp: 20
      incoming-num-tcp: 20

      # As TCP and TLS streams queue up multiple results, the amount of memory used for these buffers
      # does not exceed this number, otherwise the responses are dropped. This manages the total memory
      # usage of the server (under heavy use), the number of requests that can be queued up per
      # connection is also limited, with further requests waiting in TCP buffers. Default is 4 megabytes.
      # Requires unbound v1.9.0+
      stream-wait-size: 16m

      # Requires unbound v1.8.0+
      edns-tcp-keepalive: yes

#   forward-zone:
#       name: "."
#       forward-addr: 1.1.1.1@853#one.one.one.one
#       forward-addr: 1.0.0.1@853#one.one.one.one
#       # If a forwarded query is met with a SERVFAIL error, and this option is enabled,
#       # unbound will fall back to normal recursive resolution for this query
#       # as if no query forwarding had been specified.
#       forward-first: yes
#       # Enabled or disable whether the queries to this forwarder use TLS for transport.
#       # Requires tls-cert-bundle
#       forward-ssl-upstream: yes
#       # Disable caching when forwarding since dnsmasq is already doing that.
#       # Requires unbound v1.8.0+
#       forward-no-cache: yes



# unbound_server:
#   # The actual buffer size is determined by msg-buffer-size. Do not set higher than that value.
#   # A value of 1472 can fix fragmentation reassembly problems, usually seen as timeouts.
#   edns-buffer-size: 4096
#   # Enough for 64 Kb packets, the maximum DNS message size. No message larger than this can be sent
#   # or received. Can be reduced to use less memory, but some requests for DNS data, such
#   # as for huge resource records, will result in a SERVFAIL reply to the client.
#   msg-buffer-size: 65552
#   # If more queries arrive that need servicing, and no queries can be jostled out,
#   # then the queries are dropped.
#   num-queries-per-thread: 1024
#   # Set to a value (msec) that usually results in one roundtrip to the authority  servers.
#   # If too many queries arrive, then 50% of the queries are allowed to run to completion,
#   # and the other 50% are replaced with the new incoming query if they have already spent more than
#   # their allowed time. Protects against denial of service by slow queries or high query rates.
#   jostle-timeout: 200
#   # This prevents very delayed answer packets from the upstream (recursive) servers from bouncing
#   # against closed ports and setting off all sort of close-port counters, with eg. 1500 msec.
#   delay-close: 0
#   # The  wait  time  in  msec  for  waiting for an unknown server to reply.
#   # Increase this if you are behind a slow satellite link, to eg. 1128.
#   # That would then avoid re-querying every initial query because it times out.
#   unknown-server-time-limit: 376
#   # Allows you to bind to non-local interfaces. For example for non-existent IP addresses
#   # that are going to exist later on, with host failover configuration.
#   ip-transparent: 'no'
#   ip-freebind: 'no'
#   # Time to live maximum for RRsets and messages in the cache.
#   cache-max-ttl: 86400
#   # Time to live minimum for RRsets and messages in the cache.
#   cache-min-ttl: 0
#   # Time to live maximum for negative responses. This applies to nxdomain and nodata answers.
#   cache-max-negative-ttl: 3600
#   # Time to live for entries in the host cache.
#   infra-host-ttl: 900
#   # Number of hosts for which information is cached.
#   infra-cache-numhosts: 10000
#   # Lower limit for dynamic retransmit timeout calculation in infrastructure cache (msec).
#   infra-cache-min-rtt: 50
#   # The period Unbound will wait for a query on a TCP connection.
#   tcp-idle-timeout: 30000
#   # Requires unbound v1.8.0+
#   edns-tcp-keepalive: 'no'
#   # The period Unbound will wait for a query on a TCP connection when EDNS TCP Keepalive is active.
#   # Requires unbound v1.8.0+
#   edns-tcp-keepalive-timeout: 120000
#   # Requires tls-cert-bundle
#   ssl-upstream: 'no'
#   # Required for TLS upstream forwarding
#   # Requires unbound v1.7.0+
#   tls-cert-bundle: '/etc/pki/tls/certs/ca-bundle.crt'
#   # Allow this domain, and all its subdomains to contain private addresses.
#   private-domain: "{{ local_domain }}"
#   # Turning it on gives about 10 percent more traffic and load on the machine,
#   # but popular items do not expire from the cache.
#   prefetch: 'no'
#   # This lowers the latency of requests, but uses more CPU. If the cache is set to 0, it is no use.
#   prefetch-key: 'no'
#   # The default root hints may become outdated when servers change,
#   # therefore it is good practice to use a root-hints file.
#   root-hints: /var/lib/unbound/root.hints
#   # Directory containing this file has to be owned by unbound user
#   auto-trust-anchor-file: /var/lib/unbound/root.key
#   # In order to use files in /var/lib/unbound/
#   chroot: ""
