---
# community.docker.docker_compose currently does not support docker-compose >= 2.0.0
- name: Restart WireGuard
  become: true
  ansible.builtin.command:
    cmd: docker compose down
    chdir: "{{ wireguard_compose_dir }}"
  notify: Start WireGuard

- name: Start WireGuard
  become: true
  ansible.builtin.command:
    cmd: docker compose up -d
    chdir: "{{ wireguard_compose_dir }}"
