---
- name: Create directories
  become: true
  ansible.builtin.file:
    path: "{{ haproxy_configuration_dir }}"
    state: directory
    mode: '755'

- name: Add Docker compose file
  become: true
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ haproxy_configuration_dir }}/docker-compose.yml"
    mode: '644'
  notify: Restart haproxy

- name: Add configuration file
  become: true
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: "{{ haproxy_configuration_dir }}/haproxy.cfg"
    mode: '644'
  notify:
    - Restart haproxy
