---
- name: Create directories
  become: true
  ansible.builtin.file:
    path: "{{ haproxy_compose_dir }}"
    state: directory
    mode: '755'

- name: Add Docker compose file
  become: true
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ haproxy_compose_dir }}/docker-compose.yml"
    mode: '644'

- name: Add configuration file
  become: true
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: "{{ haproxy_compose_dir }}/haproxy.cfg"
    mode: '644'
  register: _configuration_files

- name: Stop docker services
  become: true
  ansible.builtin.command:
    cmd: docker compose down
    chdir: "{{ inadyn_compose_dir }}"
  when: _configuration_files is changed

- name: Start haproxy
  become: true
  ansible.builtin.command:
    cmd: docker compose up -d
    chdir: "{{ haproxy_compose_dir }}"
  register: _docker_compose_up_result
  changed_when: "'Running' not in _docker_compose_up_result.stderr"
