---
vaultwarden_version: 'latest'
# Automatically pull the most recent release from GitHub (rate limited).
vaultwarden_web_vault_latest_release: false
vaultwarden_web_vault_version: 'v2023.8.2'
vaultwarden_web_vault_enabled: true

# Set an admin token (password) to enable the admin page.
# vaultwarden_admin_token:
# Configuration in the admin page overrides the environment variables.
# Enable to reset those overrides.
vaultwarden_reset_admin_config: false

vaultwarden_disable_2fa_remember: false
vaultwarden_require_device_email: false
vaultwarden_signups_allowed: true
vaultwarden_signups_verify: false
vaultwarden_invitations_allowed: true
vaultwarden_password_iterations: 2000000
vaultwarden_show_password_hint: false

# This needs to be set to the URL used to access the server, including 'http[s]://' and port, if it's different than the default.
vaultwarden_domain: "{{ 'https' if vaultwarden_tls is defined else 'http'}}://{{ vaultwarden_rocket_address }}:{{ vaultwarden_rocket_port }}"

# vaultwarden_yubico:
#   client_id:
#   secret_key:
#   server:

vaultwarden_authenticator_disable_time_drift: false

# vaultwarden_smtp:
#   host: smtp.example.com
#   from: vaultwarden@example.com
vaultwarden_smtp_from_name: 'Vaultwarden'
# Port defaults to 465 if explicit TLS is enabled, otherwise default to 587 if SSL is enabled and 25 if not.
vaultwarden_smtp_port: "{{ 465 if vaultwarden_smtp_security else 587 }}"
# Setting force_tls would force the use of an explicit TLS connection, instead of upgrading an insecure one with STARTTLS.
vaultwarden_smtp_security: starttls
# vaultwarden_smtp_credentials:
#   username:
#   password:
# vaultwarden_smtp_auth_mechanism: 'Plain'
vaultwarden_smtp_timeout: 15

# HaveIBeenPwned API Key, request it here: https://haveibeenpwned.com/API/Key
# vaultwarden_hibp_api_key:
