---
- name: Build Bitwarden server
  hosts: bitwardenservers
  tasks:
    - import_role:
        name: vaultwarden

    - name: 'Install sqlite for backup purposes'
      become: true
      package:
        name: sqlite
        state: present

  post_tasks:
    - import_role:
        name: smb_mount

    - name: Schedule sqlite3 database backup
      become: true
      cron:
        name: "Dump sqlite3 database to backup file"
        job: >
          /usr/bin/sqlite3
          {{ vaultwarden_data_folder }}/db.sqlite3
          ".backup ' {{ vaultwarden_data_folder }}/backup.sqlite3'"
        hour: '3'
        minute: '0'
        state: present

    - name: Schedule backup to network drive
      become: true
      cron:
        name: "Back up vaultwarden to network drive"
        job: >
          /usr/bin/tar
          -zcf
          {{ smb_backup_folder }}/data.tar.gz
          {{ vaultwarden_data_folder }}
        hour: '4'
        minute: '0'
        state: present
