---
- name: Configure Gitea server
  hosts: gitea
  tasks:
    - import_role:
        name: gitea

  post_tasks:
    - import_role:
        name: smb_mount

    - name: Schedule backup to network drive
      become: true
      cron:
        name: "Back up Gitea to network drive"
        job: "mv tar -czf {{ smb_backup_dir }}/gitea-dump.zip {{ gitea_data_dir }}"
        hour: '4'
        minute: '0'
        state: present
