---
# - name: Configure DoT stub resolver
#   hosts: dnsservers
#   tasks:
#     - import_role:
#         name: stubby

- name: Configure DNS servers
  hosts: dnsservers

  tasks:
    - import_role:
        name: dns

# - name: Open DNS port
#   hosts: dnsservers
#   tasks:
#     - import_role:
#         name: firewall
#       vars:
#         firewall_rules:
#           # Internal DNS servers should only respond to local UDP queries (prevents DDoS amplification attacks against external networks)
#           - { port: '53', proto: 'udp', src: '10.0.0.0/8', comment: 'Internal DNS' }
#           - { port: '53', proto: 'udp', src: '172.16.0.0/12', comment: 'Internal DNS' }
#           - { port: '53', proto: 'udp', src: '192.168.0.0/16', comment: 'Internal DNS' }
#           - { port: '53', proto: 'tcp', comment: 'DNS' }

# - name: Open DHCP port
#   hosts: pihole_dhcp
#   tasks:
#     - import_role:
#         name: firewall
#       vars:
#         firewall_rules:
#           - { port: '67', proto: 'udp', comment: 'DHCP' }

# - name: Configure DoT/recursive resolver
#   hosts: unboundservers
#   tasks:
#     - import_role:
#         name: unbound

#     # This is for busy servers that handle spikes in answer traffic,
#     # otherwise packets might be dropped with error 'send: resource temporarily unavailable'.
#     # Despite my best efforts, Unbound is slow compared to Stubby, about 100 qps on one core of a J4105.
#     - name: 'unbound: Increase buffer size'
#       become: true
#       sysctl:
#         name: "{{ item }}"
#         value: '4194304'
#         state: present
#       loop:
#         - 'net.core.wmem_max'
#         - 'net.core.rmem_max'

# - name: Configure DDNS
#   hosts: ddns
#   tasks:
#     - import_role:
#         name: inadyn

#     - block:
#         - name: Make sure cron is installed
#           become: true
#           package:
#             name: cronie
#             state: present
#       rescue:
#         - name: Make sure cron is installed
#           become: true
#           package:
#             name: cron
#             state: present

#     - name: Configure regular DDNS updates
#       cron:
#         name: 'Update DuckDNS domains'
#         job: >
#           echo url="https://www.duckdns.org/update?domains={{ duckdns_domains | join(',') | quote }}&token={{ duckdns_token | quote }}&ip="
#           | curl -s -o ~/duck.log -K -
#         minute: '*/10'
#         state: present
#       tags: update_config
