---
- name: Configure game servers
  hosts: gameservers
  pre_tasks:
    - name: Install python(3)-apt for package facts
      become: true
      package:
        name: python*-apt
      when: ansible_os_family == 'Debian'
  roles:
    - role: linuxgsm

- name: Configure CSGO server
  hosts: csgo
  roles:
    - role: firewall
      vars:
        firewall_rules:
          - { port: '27015', proto: 'tcp', comment: 'CSGO game server' }
          - { port: '27015', proto: 'udp', comment: 'CSGO game server' }
          - { port: '27020', proto: 'udp', comment: 'SourceTV' }

- name: Configure Valheim server
  hosts: valheim
  roles:
    - role: firewall
      vars:
        firewall_rules:
          - { port: '2456:2458', proto: 'udp', comment: 'Valheim' }
  post_tasks:
    - import_role:
        name: smb_mount
    - name: Install tar for archiving
      become: true
      package:
        name: tar
    - name: Set Valheim world file archive dir
      set_fact:
        valheim_archive_dir: "/home/{{ linuxgsm_user | quote }}/world_backup"
    - name: Create archive dir
      file:
        path: "{{ valheim_archive_dir }}"
        state: directory
    - name: Schedule Valheim world files archival
      cron:
        name: Archive Valheim world files
        hour: "*/2"
        minute: "0"
        job: "/usr/bin/tar -czf \"{{ valheim_archive_dir }}/valheim_$(date -Iseconds).tar.gz\" /home/{{ linuxgsm_user | quote }}/.config/unity3d/IronGate/Valheim/worlds"
    - name: Schedule moving LinuxGSM backups to NAS
      become: true
      cron:
        name: Move Valheim backups to file server
        hour: "4"
        minute: "1"
        job: "/usr/bin/mv {{ valheim_archive_dir }}/* {{ smb_mounts.0.local_path }}"
