#!/usr/bin/env ansible-playbook
---
# TODO: Set up documentation (wiki.js or Bookstack?)
# TODO: Set up pull backups on orangepizero
# TODO: Static IP role
# TODO: Set up Syncthing
# TODO: Playbook for restoring backups
# TODO: Infrastucture provisioning (Terraform?)
# TODO: OpenSUSE Leap support
# TODO: Set up CI/CD (DroneCI?)
# TODO: Monitoring and alerts on everything
# TODO: Non-privileged LetsEncrypt implementation? (https://letsencrypt.org/docs/client-options/)
# TODO: nftables module
# TODO: Email server with SMTP relay (Mailgun/SendGrid)

- name: VyOS router config
  hosts: vyos
  roles:
    - vyos

- name: Common settings
  hosts: home
  roles:
    - common
    - role: firewall
      vars:
        firewall_policies:
          - { chain: INPUT, policy: DROP }
          - { chain: FORWARD, policy: DROP }
        firewall_rules:
          # Reject policy (ACCEPT policies for the chains, must be last rules in respective chain):
          #   -A INPUT -j REJECT --reject-with icmp-host-prohibited
          #   -A FORWARD -j REJECT --reject-with icmp-host-prohibited
          - { chain: INPUT, rule: ACCEPT, ctstate: [ ESTABLISHED, RELATED ] }
          - { chain: INPUT, rule: ACCEPT, in_interface: lo, comment: Localhost connections }
          # ICMP types and limit rules get added repeatedly on Debian
          # - { chain: INPUT, rule: ACCEPT, icmp_type: echo-request, proto: icmp, limit: 10/s, comment: Ping requests }
          # - { chain: INPUT, rule: ACCEPT, port: 22, proto: tcp, limit: 10/m, comment: SSH }
          - { chain: INPUT, rule: ACCEPT, proto: icmp, comment: Ping requests }
          - { chain: INPUT, rule: ACCEPT, port: 22, proto: tcp, comment: SSH }

- name: Install TP-Link Omada software controller
  hosts: omada
  tasks:
    - import_role:
        name: omada_controller

- import_playbook: dnsservers.yml
- import_playbook: vpnservers.yml
- import_playbook: webservers.yml
- import_playbook: dev_env.yml
- import_playbook: jellyfinservers.yml
- import_playbook: bitwardenservers.yml
- import_playbook: retropie.yml
- import_playbook: gameservers.yml
