---
home:
  hosts:
    vyos:
      ansible_host: "{{ hosts['vyos']['ipv4_address'] | ansible.utils.ipaddr('address') }}"
      ansible_user: vyos
    public-docker:
      ansible_host: "{{ hosts['public-docker']['ipv4_address'] | ansible.utils.ipaddr('address') }}"
    internal-docker:
      ansible_host: "{{ hosts['internal-docker']['ipv4_address'] | ansible.utils.ipaddr('address') }}"
    retropie:
      ansible_user: pi

dortheogallan:
  hosts:
    orangepizero.fritz.box:
      ansible_host: "{{ vpn_network_ipv4 | ansible.utils.ipaddr('2') | ansible.utils.ipaddr('address') }}"
