---
ungrouped:
  hosts:
    localhost:
home:
  hosts:
    vyos:
      ansible_host: "{{ infrastructure_hosts['vyos']['ipv4_address'] | ansible.utils.ipaddr('address') }}"
    dns:
      ansible_host: "{{ infrastructure_hosts['dns']['ipv4_address'] | ansible.utils.ipaddr('address') }}"
    public-docker:
      ansible_host: "{{ infrastructure_hosts['public-docker']['ipv4_address'] | ansible.utils.ipaddr('address') }}"
    internal-docker:
      ansible_host: "{{ infrastructure_hosts['internal-docker']['ipv4_address'] | ansible.utils.ipaddr('address') }}"
