---
# TODO: Use reverse proxy
- name: Install Jellyfin
  hosts: jellyfinservers
  pre_tasks:
    - import_role:
        name: smb_mount

  tasks:
    - import_role:
        name: jellyfin
    - import_role:
        name: firewall
      vars:
        firewall_rules:
          - { port: '8096', proto: 'tcp', comment: 'Web server HTTP' }
          - { port: '8920', proto: 'tcp', comment: 'Web server HTTPS' }
          - { port: '1900', proto: 'udp', comment: 'DLNA' }
          - { port: '7359', proto: 'udp', comment: 'DLNA' }

  post_tasks:
    - name: Set TLS certificate owner
      become: true
      file:
        path: '/var/lib/jellyfin/tls_certificate.p12'
        state: file
        owner: jellyfin
        group: jellyfin

    - name: Schedule backup to network drive
      become: true
      cron:
        name: "Back up Jellyfin to network drive"
        job: >
          /usr/bin/tar
          -zcf
          {{ smb_backup_folder }}/jellyfin.tar.gz
          /var/lib/jellyfin
        hour: '4'
        minute: '0'
        state: present
