---
- name: Install Jellyfin
  hosts: jellyfinservers
  pre_tasks:
    - import_role:
        name: smb_mount

  tasks:
    - import_role:
        name: jellyfin

  post_tasks:
    - name: Schedule backup to network drive
      become: true
      cron:
        name: "Back up Jellyfin to network drive"
        job: >
          /usr/bin/tar
          -zcf
          {{ smb_backup_dir }}/jellyfin.tar.gz
          {{ jellyfin_config_dir }}
        hour: '4'
        minute: '0'
        state: present
