---
# TODO: Use reverse proxy
- name: Install Plex
  hosts: plexservers
  pre_tasks:
    - import_role:
        name: smb_mount

  tasks:
    - import_role:
        name: plex
    - import_role:
        name: firewall
      vars:
        firewall_rules:
          - { port: '32400', proto: 'tcp', comment: 'Web server' }
          - { port: '32410:32414', proto: 'udp', comment: 'GDM discovery' }
          - { port: '1900', proto: 'udp', comment: 'DLNA' }
          - { port: '32469', proto: 'udp', comment: 'DLNA' }

  post_tasks:
    - name: Set TLS certificate owner
      become: true
      file:
        path: '/var/lib/plexmediaserver/keystore.p12'
        state: file
        owner: plex
        group: plex

    - name: Schedule backup to network drive
      become: true
      cron:
        name: "Back up plex to network drive"
        job: >
          /usr/bin/tar
          -zcf
          {{ smb_backup_folder }}/plex.tar.gz
          /var/lib/plexmediaserver
        hour: '4'
        minute: '0'
        state: present
