---
stubby_version: master

# Loglevel 0-7, higher numbers log more messages
stubby_log_level: 5

stubby_listen_addresses:
  - 0.0.0.0@53
  - 0::@53

stubby_opportunistic_tls: false
# These options require double quotes in the config file so they get their own variables to make Ansible configuration simpler.
stubby_appdata_dir: # /var/cache/stubby
stubby_tls_ca_path: # /etc/ssl/certs/
stubby_tls_cipher_list: # 'EECDH+AESGCM:EECDH+CHACHA20'
stubby_tls_ciphersuites: # 'TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256'
stubby_dnssec_trust_anchors: # /etc/unbound/getdns-root.key

# Remaining options are set by putting them in a mapping.
stubby_options: {}
  # tls_query_padding_blocksize: 128
  # edns_client_subnet_private: 1
  # round_robin_upstreams: 1
  # idle_timeout: 10000
  # tls_connection_retries: 5
  # tls_backoff_time: 300
  # limit_outstanding_queries: 100
  # timeout: 1000
  # tls_min_version: GETDNS_TLS1_2
  # tls_max_version: GETDNS_TLS1_3
  # dnssec: GETDNS_EXTENSION_TRUE
  # trust_anchors_backoff_time: 2500

# Stubby uses an odd mix of JSON and YAML for its configuration that does not quite support standard YAML,
# so the easiest way to set upstream servers is to simply copy from the examples into a string.
stubby_upstream: |
  ####### IPv4 addresses ######
  # The Surfnet/Sinodun servers
    - address_data: 145.100.185.15
      tls_auth_name: "dnsovertls.sinodun.com"
      tls_pubkey_pinset:
        - digest: "sha256"
          value: 62lKu9HsDVbyiPenApnc4sfmSYTHOVfFgL3pyB+cBL4=
    - address_data: 145.100.185.16
      tls_auth_name: "dnsovertls1.sinodun.com"
      tls_pubkey_pinset:
        - digest: "sha256"
          value: cE2ecALeE5B+urJhDrJlVFmf38cJLAvqekONvjvpqUA=
  # The getdnsapi.net server
    - address_data: 185.49.141.37
      tls_auth_name: "getdnsapi.net"
      tls_pubkey_pinset:
        - digest: "sha256"
          value: foxZRnIh9gZpWnl+zEiKa0EJ2rdCGroMWm02gaxSc9Q=
  ####### IPv6 addresses ######
  # The Surfnet/Sinodun servers
    - address_data: 2001:610:1:40ba:145:100:185:15
      tls_auth_name: "dnsovertls.sinodun.com"
      tls_pubkey_pinset:
        - digest: "sha256"
          value: 62lKu9HsDVbyiPenApnc4sfmSYTHOVfFgL3pyB+cBL4=
    - address_data: 2001:610:1:40ba:145:100:185:16
      tls_auth_name: "dnsovertls1.sinodun.com"
      tls_pubkey_pinset:
        - digest: "sha256"
          value: cE2ecALeE5B+urJhDrJlVFmf38cJLAvqekONvjvpqUA=
  # The getdnsapi.net server
    - address_data: 2a04:b900:0:100::38
      tls_auth_name: "getdnsapi.net"
      tls_pubkey_pinset:
        - digest: "sha256"
          value: foxZRnIh9gZpWnl+zEiKa0EJ2rdCGroMWm02gaxSc9Q=
