---
# Based on information from:
# https://www.reddit.com/r/pihole/comments/7oyh9m/guide_how_to_use_pihole_with_stubby/
# https://dnsprivacy.org/wiki/pages/viewpage.action?pageId=3145786
# https://github.com/getdnsapi/getdns/blob/develop/README.md#building-and-external-dependencies
# https://lektor.getdnsapi.net/quick-start/cmake-quick-start/
# https://github.com/getdnsapi/stubby/tree/master/systemd

- name: Check systemd version
  shell: systemctl --version | awk '{print $2}'
  register: stubby_systemd_version
  changed_when: false
  check_mode: false

- name: (CentOS 8) Enable PowerTools repo
  become: true
  ini_file:
    path: /etc/yum.repos.d/CentOS-PowerTools.repo
    section: PowerTools
    option: enabled
    value: "1"
  when:
    - ansible_distribution == 'CentOS'
    - ansible_distribution_version is version('8', '>=')

- name: Install build dependencies
  become: true
  package:
    name: "{{ stubby_build_dependencies }}"
    state: present

- name: Create directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '755'
  loop:
    - "{{ stubby_install_dir }}/src"
    - "{{ stubby_conf_dir }}"

- name: Download source tarball
  get_url:
    url: "https://getdnsapi.net/dist/getdns-{{ stubby_release }}.tar.gz"
    dest: /var/tmp/getdns-{{ stubby_release }}.tar.gz
  register: stubby_src_tarball

- name: Extract files to destination
  become: true
  unarchive:
    src: "{{ stubby_src_tarball.dest }}"
    dest: "{{ stubby_install_dir }}/src"
    remote_src: true
    creates: "{{ stubby_src_dir }}"

- name: Set build options
  become: true
  command: "cmake -D{{ stubby_build_options | join(' -D') }} ."
  args:
    chdir: "{{ stubby_src_dir }}"
    creates: "{{ stubby_makefile_path }}"

- name: Build getdns
  become: true
  command: make -j{{ stubby_make_job_count }} install
  args:
    chdir: "{{ stubby_src_dir }}"
    creates: "{{ stubby_bin_path }}"
  notify: Restart Stubby

- name: Link libgetdns shared library
  become: true
  command: ldconfig
  changed_when: false

- name: Symlink Stubby conf file if it does not exist
  become: true
  file:
    src: "{{ stubby_install_dir }}/etc/stubby/stubby.yml"
    dest: "{{ stubby_conf_file }}"
    state: link
    owner: root
    group: root
  register: stubby_conf_file_status
  failed_when: stubby_conf_file_status.state not in ['file', 'link']

- name: Create Stubby cache dir
  become: true
  template:
    src: stubby.conf.j2
    dest: /usr/lib/tmpfiles.d/stubby.conf
    owner: root
    group: root
    mode: '644'
  when: stubby_systemd_version.stdout_lines[0] | int < 235

- name: Create Stubby service
  become: true
  template:
    src: stubby.service.j2
    dest: /lib/systemd/system/stubby.service
    owner: root
    group: root
    mode: '644'

- name: Enable Stubby service
  become: true
  service:
    name: stubby
    masked: false
    enabled: true
    daemon_reload: true
