---
- name: Get root hints for recursive DNS
  become: true
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    owner: "{{ unbound_user }}"
    group: "{{ unbound_user }}"
    mode: '644'
  loop:
    - url: "{{ unbound_root_hints_url }}"
      dest: "{{ unbound_root_hints_file }}"
    - url: "{{ unbound_root_certificate_url }}"
      dest: "{{ unbound_root_certificate }}"
  register: unbound_trust_anchor_deps

- name: Configure automatic root hint-updates every month
  become: true
  cron:
    name: Update DNS root hints
    job: "wget {{ unbound_root_hints_url | quote }} -O {{ unbound_root_hints_file | quote }}"
    special_time: 'monthly'
    state: present

- name: Create trust anchor
  become: true
  service:
    name: unbound-anchor
    state: started
