---
- name: Upload configuration script
  ansible.builtin.template:
    src: commands.sh.j2
    dest: ./commands.sh
    mode: '700'
  register: vyos_configuration_script

- block:
    # Run commands and say yes to any prompts.
    - name: Run script
      ansible.builtin.shell:
        cmd: yes | ./commands.sh
        executable: /bin/vbash

    - name: Save changes
      ansible.builtin.shell:
        cmd: |
          source /opt/vyatta/etc/functions/script-template
          configure
          confirm
          save
        executable: /bin/vbash
  when: vyos_configuration_script is changed
