---
- name: Install SMB tools
  become: true
  ansible.builtin.package:
    name: cifs-utils
    state: present

- block:
    - name: Create directories
      become: true
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: directory
        owner: root
        group: root
        mode: '600'
      loop:
        - path: "{{ smb_credential_dir }}"

    - name: Add SMB credentials
      become: true
      ansible.builtin.template:
        src: credentials.j2
        dest: "{{ smb_credential_dir }}/{{ item.0 }}"
        owner: root
        group: root
        mode: '600'
      loop: "{{ smb_mounts.items() }}"
      no_log: true

    - name: Mount volume
      become: true
      ansible.builtin.mount:
        path: "{{ item.1.local_path }}"
        src: "{{ item.1.network_path }}"
        state: mounted
        fstype: cifs
        opts: "{{ item.1.options }},credentials={{ smb_credential_dir }}/{{ item.0 }}"
      loop: "{{ smb_mounts.items() }}"
  when: smb_mounts is defined
