---
- name: (Debian) Install dependencies for repository key verification
  become: true
  package:
    name:
      - gpg
      - ca-certificates
    state: present

- name: (Debian) Add repository keys
  become: true
  apt_key:
    url: "{{ item }}"
    state: present
  loop:
    - "https://www.mongodb.org/static/pgp/server-4.2.asc"
    - "https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public"

- name: (Debian) Add repositories
  become: true
  apt_repository:
    repo: "deb {{ item }}"
    state: present
  loop:
    - "https://repo.mongodb.org/apt/debian {{ ansible_distribution_release }}/mongodb-org/4.2 main"
    - "https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ {{ ansible_distribution_release }} main"

- name: (Debian) Install Java 8 and MongoDB
  become: true
  package:
    name:
      - adoptopenjdk-8-hotspot
      - mongodb-org-server
    state: present
