---
- name: Create directories
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: '755'
  loop:
    - path: "{{ omada_compose_dir }}"

- name: Add Docker compose file
  become: true
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ omada_compose_dir }}/docker-compose.yml"
    mode: '640'

- name: Start Omada
  become: true
  ansible.builtin.command:
    cmd: docker compose up -d
    chdir: "{{ omada_compose_dir }}"
  register: _docker_compose_up_result
  changed_when: "'Running' not in _docker_compose_up_result.stderr"
