---
- name: Create directories
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: '755'
  loop:
    - path: "{{ omada_compose_dir }}"

- name: Add Docker compose file
  become: true
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ omada_compose_dir }}/docker-compose.yml"
    mode: '640'

- name: Start Omada
  become: true
  community.docker.docker_compose_v2:
    project_src: "{{ omada_compose_dir }}"
    state: "present"
    pull: "always"
    recreate: "auto"
    remove_orphans: true
