---
- name: (RedHat) Add package repositories
  become: true
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.name }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: true
    gpgkey: "{{ item.gpgkey }}"
    repo_gpgcheck: true
    enabled: true
    state: present
  loop:
    - name: MongoDB
      description: Official MongoDB releases
      baseurl: 'https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.2/x86_64/'
      gpgkey: 'https://www.mongodb.org/static/pgp/server-4.2.asc'

- name: (RedHat) Install Java 8 and MongoDB
  become: true
  yum:
    name:
      - java-1.8.0-openjdk-headless
      - mongodb-org-server
    state: present

# Required for python2-pip
- name: (CentOS 7) Enable EPEL repository
  become: true
  yum:
    name: epel-release
    state: present
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version | int == 7
