---
- name: Create env file
  template:
    src: gitea.env.j2
    dest: "{{ gitea_env_path }}"
    owner: "{{ gitea_user }}"
    group: "{{ gitea_user }}"
    mode: '644'
  notify: Restart Gitea

# TODO: Locking this file is possible https://docs.gitea.io/en-us/install-from-binary/#create-required-directory-structure
- name: Initial config (only first install)
  copy:
    content: "{{ gitea_init_conf }}"
    dest: "{{ gitea_conf_dir }}/custom/conf/app.ini"
    owner: "{{ gitea_user }}"
    group: "{{ gitea_user }}"
    mode: '640'
    force: false
  notify: Restart Gitea
