---
# https://docs.gitea.com/installation/install-with-docker
- name: Create directories
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: '755'
  loop:
    - path: "{{ gitea_compose_dir }}"

- name: Add Docker compose file
  become: true
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ gitea_compose_dir }}/docker-compose.yml"
    mode: '640'
  notify: Restart Gitea
