---
# community.docker.docker_compose currently does not support docker-compose >= 2.0.0
- name: Restart Omada
  become: true
  ansible.builtin.command:
    cmd: docker compose down --timeout 30
    chdir: "{{ omada_compose_dir }}"
  notify: Start Omada

- name: Start Omada
  become: true
  ansible.builtin.command:
    cmd: docker compose up -d
    chdir: "{{ omada_compose_dir }}"
