---
# - name: (Debian) Disable UFW
#   become: true
#   ufw:
#     state: disabled

- block:
    # TODO: Might save service-managed rules (e.g. WireGuard). Write direct to config file and load that instead?
    - name: (Debian) Get iptables rules
      become: true
      command: iptables-save
      register: firewall_iptables_save
      changed_when: false

    - name: (Debian) Create iptables conf dir
      become: true
      file:
        path: /etc/iptables
        state: directory
        mode: '755'

    - name: (Debian) Save iptables rules
      become: true
      copy:
        content: "{{ firewall_iptables_save.stdout }}"
        dest: /etc/iptables/rules.v4
      # iptables-save output includes a timestamp, not idempotent
      changed_when: false
  tags: firewall_reset_all

- name: (Debian) Load iptables rules at boot
  become: true
  copy:
    src: iptables-preup
    dest: /etc/network/if-pre-up.d/iptables
    mode: '755'
    backup: true
