---
# - block:
#     - name: Reset default policies
#       become: true
#       iptables:
#         chain: "{{ item }}"
#         policy: ACCEPT
#       loop:
#         - INPUT
#         - FORWARD
#         - OUTPUT

#     - name: Flush iptables rules
#       become: true
#       iptables:
#         table: "{{ item }}"
#         flush: true
#       loop:
#         - filter
#         - nat

#     - name: Prevent flushing again
#       set_fact:
#         firewall_already_reset: true
#   when: not firewall_already_reset
#   tags:
#     - firewall_reset_all
#     - never

- name: Set iptables rules
  become: true
  iptables:
    table: "{{ item.table | default(omit) }}"
    chain: "{{ item.chain | default('INPUT') }}"
    jump: "{{ item.rule | default('ACCEPT') }}"
    ctstate: "{{ item.ctstate | default(omit) }}"
    source: "{{ item.src | default(omit) }}"
    in_interface: "{{ item.in_interface | default(omit) }}"
    destination: "{{ item.dest | default(omit) }}"
    destination_port: "{{ item.port | default(omit) }}"
    icmp_type: "{{ item.icmp_type | default(omit) }}"
    protocol: "{{ item.proto | default(omit) }}"
    ip_version: "{{ item.ip_version | default(omit) }}"
    limit: "{{ item.limit | default(omit) }}"
    comment: "{{ item.comment | default(omit) }}"
  when: firewall_rules is defined
  loop: "{{ firewall_rules }}"

- name: Set iptables default policies
  become: true
  iptables:
    chain: "{{ item.chain | default('INPUT') }}"
    policy: "{{ item.policy }}"
  when: firewall_policies is defined
  loop: "{{ firewall_policies }}"
