---
# TODO: Deletes all iptables rules, but leaves policies in place
# - name: (RedHat) Disable firewalld
#   become: true
#   ansible.builtin.service:
#     name: firewalld
#     enabled: false
#     state: stopped

# TODO: Broken on Fedora
# TODO: Saves service-managed rules (e.g. WireGuard). Write direct to config file and load that instead?
- name: (RedHat) Save iptables rules
  become: true
  ansible.builtin.command: service iptables save
  args:
    warn: false
  changed_when: false
  ignore_errors: true
  tags: firewall_reset_all

- name: (RedHat) Enable iptables
  become: true
  ansible.builtin.service:
    name: iptables
    state: started
    enabled: true
