---
- name: Install firewall
  become: true
  package:
    name: ufw
    state: present

- name: Set UFW rules
  become: true
  ufw:
    rule: "{{ item.rule | default('allow') }}"
    from_ip: "{{ item.src | default('any') }}"
    to_ip: "{{ item.dest | default('any') }}"
    to_port: "{{ item.port | default('any') }}"
    proto: "{{ item.proto | default('any') }}"
    comment: "{{ item.comment | default(omit) }}"
  when: firewall_rules is defined
  loop: "{{ firewall_rules }}"

# When using REJECT as default policy, ufw may end up rejecting rules that are added outside of ufw and after ufw is started.
# https://github.com/jbq/ufw/blob/237a7bb4e262ab65266b6c1d996eb71ec6d84954/README#L129
- name: Set UFW default policies
  become: true
  ufw:
    direction: "{{ item.direction | default('incoming') }}"
    default: "{{ item.policy }}"
  when: firewall_policies is defined
  loop: "{{ firewall_policies }}"

- name: Set UFW state
  become: true
  ufw:
    state: "{{ firewall_state }}"
  when: firewall_state is defined
