---
- name: Create directories
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: '755'
  loop:
    - path: "{{ inadyn_compose_dir }}"

- name: Apply In-A-Dyn config
  become: true
  ansible.builtin.template:
    src: inadyn.conf.j2
    dest: "{{ inadyn_config_path }}"
    # Contains secrets, must not be world-readable
    mode: '600'

- name: Add Docker compose file
  become: true
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ inadyn_compose_dir }}/docker-compose.yml"
    mode: '640'

- name: Start In-A-Dyn
  become: true
  ansible.builtin.command:
    cmd: docker compose up -d
    chdir: "{{ inadyn_compose_dir }}"
