---
- name: Fail on unsupported systems
  fail:
    msg: In-A-Dyn v2.0 and later versions require libConfuse 3.0 or later
  when:
    - (ansible_distribution == 'CentOS' and ansible_distribution_major_version | int < 8) or
      (ansible_distribution == 'Debian' and ansible_distribution_major_version | int < 9) or
      (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version | int < 18) or
      (ansible_distribution == 'Fedora' and ansible_distribution_major_version | int < 25)
    - not inadyn_ignore_unsupported_distro

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Remove existing In-A-Dyn files to force a reinstall
  become: true
  file:
    path: "{{ item }}"
    state: absent
  when: inadyn_force_reinstall
  loop:
    - "{{ inadyn_src_makefile }}"
    - "{{ inadyn_src_binary }}"
    - "{{ inadyn_installed_binary }}"
