---
wireguard_compose_dir: "{{ docker_compose_dir }}/wireguard/"
wireguard_version: latest

# Make sure the key pair you provide is well-protected (ansible-vault)
# wireguard_server_keys: { private: 'placeholder1', public: 'placeholder2' }
wireguard_interface_name: wg0
wireguard_addresses:
  - '172.16.0.1/24'
wireguard_listenport: 51820
wireguard_default_persistent_keepalive: 55

wireguard_fwmark: 'off'
# If not specified, the MTU is automatically determined from the endpoint addresses or the system default route
wireguard_mtu: ''
wireguard_table: 'auto'
wireguard_preup: []
wireguard_predown: []
wireguard_postup:
  - "iptables -A INPUT -p udp --dport {{ wireguard_listenport }} -j ACCEPT"
  - "iptables -A FORWARD -i %i -j ACCEPT"
  - "iptables -A FORWARD -o %i -j ACCEPT"
  - "iptables -t nat -A POSTROUTING -s {{ wireguard_addresses | ansible.utils.ipaddr('network/prefix') | join(',') }} -j MASQUERADE"
wireguard_postdown:
  - "iptables -D INPUT -p udp --dport {{ wireguard_listenport }} -j ACCEPT"
  - "iptables -D FORWARD -i %i -j ACCEPT"
  - "iptables -D FORWARD -o %i -j ACCEPT"
  - "iptables -t nat -D POSTROUTING -s {{ wireguard_addresses | ansible.utils.ipaddr('network/prefix') | join(',') }} -j MASQUERADE"

# Peers are provided as a mapping from name to the options as key-value pairs.
# PublicKey and AllowedIPs are required.
wireguard_peers:
  # example_name:
  #   PublicKey: 'example1pubk'
  #   PresharedKey: 'example1psk'
  #   AllowedIPs: '172.16.0.2/32'
  #   Endpoint: 'example.org:51820'
  #   PersistentKeepalive: 0
  # example_name_2:
  #   PublicKey: 'example2pubk'
  #   PresharedKey: 'example2psk'
  #   AllowedIPs: '172.16.0.3/32'
  #   Endpoint: 'example.org:51820'
  #   PersistentKeepalive: 25
