---
galaxy_info:
  author: Niklas Elmose Andersen
  description: Unbound - Validating, recursive, and caching DNS resolver

  license: "license (0BSD, MIT-0)"
  min_ansible_version: 2.2
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - 29
        - 30
    - name: Debian
      versions:
        - jessie
        - stretch
        - buster
    - name: Ubuntu
      versions:
        - xenial
        - bionic
  galaxy_tags:
    - unbound
    - dns
    - resolver
