---
# Every version of vaultwarden uses a new Rust toolchain
# Both Rust toolchains and vaultwarden build directories use a lot of disk space

- name: Find any old vaultwarden src directories
  find:
    paths: "{{ vaultwarden_src_dir }}"
    recurse: false
    file_type: directory
    patterns:
      - 'v*'
    excludes:
      - "v{{ vaultwarden_version }}"
  register: vaultwarden_existing_src

- name: Get name(s) of old Rust toolchain(s)
  slurp:
    src: "{{ item.path }}/rust-toolchain"
  loop: "{{ vaultwarden_existing_src.files }}"
  register: vaultwarden_existing_toolchains

- name: Print name(s) of old Rust toolchain(s)
  debug:
    msg: "{{ item.content | b64decode }}"
    verbosity: 1
  loop: "{{ vaultwarden_existing_toolchains.results }}"

- name: Remove old Rust toolchain(s)
  command: "{{ ansible_user_dir | quote }}/.cargo/bin/rustup toolchain uninstall {{ item.content | b64decode | quote }}"
  args:
    removes: "{{ ansible_user_dir }}/.rustup/toolchains/{{ item.content | b64decode }}*"
  loop: "{{ vaultwarden_existing_toolchains.results }}"

- name: Remove any old vaultwarden src directories
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ vaultwarden_existing_src.files }}"
