---
- name: Create directories
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: '755'
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
  loop:
    - path: "{{ vaultwarden_compose_dir }}"
    - path: "{{ vaultwarden_data_dir }}"
      owner: "{{ docker_remap_user }}"
      group: "{{ docker_remap_user }}"
    - path: "{{ vaultwarden_web_vault_dir }}"
      owner: "{{ docker_remap_user }}"
      group: "{{ docker_remap_user }}"

- name: Add Docker compose file
  become: true
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ vaultwarden_compose_dir }}/docker-compose.yml"
    mode: '640'

- ansible.builtin.include_tasks: web_vault.yml
  when: vaultwarden_web_vault_enabled

- name: Start Vaultwarden
  become: true
  ansible.builtin.command:
    cmd: docker compose up -d
    chdir: "{{ vaultwarden_compose_dir }}"
  register: _docker_compose_up_result
  changed_when: "'Running' not in _docker_compose_up_result.stderr"
