---
- name: Create directories
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    mode: '750'
  loop:
    - path: "{{ vaultwarden_web_vault_folder }}"
    - path: "{{ vaultwarden_env_dir }}"

- name: Reset settings override by admin
  become: true
  ansible.builtin.file:
    path: "{{ vaultwarden_data_folder }}/config.json"
    state: absent
  when: vaultwarden_reset_admin_config
  notify: Restart vaultwarden
  tags: update_config

- name: Add Docker compose file
  become: true
  ansible.builtin.template:
    src: docker-compose.yml
    dest: /etc/docker_compose/vaultwarden/docker-compose.yml
    mode: '644'
  notify: Start vaultwarden
  tags: update_config

- include_tasks: web_vault.yml
  when: vaultwarden_web_vault_enabled
