---
- name: Create directories
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: '755'
  loop:
    - path: "{{ vaultwarden_compose_dir }}"
    - path: "{{ vaultwarden_data_dir }}"

- name: Reset settings override by admin
  become: true
  ansible.builtin.file:
    path: "{{ vaultwarden_data_dir }}/config.json"
    state: absent
  when: vaultwarden_reset_admin_config
  notify: Restart Vaultwarden

- name: Add Docker compose file
  become: true
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ vaultwarden_compose_dir }}/docker-compose.yml"
    mode: '640'
  notify: Restart Vaultwarden

- ansible.builtin.include_tasks: web_vault.yml
  when: vaultwarden_web_vault_enabled
