---
- block:
  # https://developer.github.com/v3/repos/releases/#get-the-latest-release
  - name: Get the latest non-prerelease tag on GitHub
    # The GitHub API is rate limited
    run_once: true
    uri:
      url: 'https://api.github.com/repos/dani-garcia/bw_web_builds/releases/latest'
    register: vaultwarden_web_vault_release_latest

  - name: Select latest vaultwarden release
    set_fact:
      vaultwarden_web_vault_version: "{{ vaultwarden_web_vault_release_latest.json.tag_name }}"
  when: vaultwarden_latest_release

# This depends on the git module creating the destination folder during the build step (build.yml)
- name: Download web-vault files
  get_url:
    url: "https://github.com/dani-garcia/bw_web_builds/releases/download/\
          {{ vaultwarden_web_vault_version }}/bw_web_{{ vaultwarden_web_vault_version }}.tar.gz"
    dest: "{{ vaultwarden_web_vault_tarball }}"
    mode: '640'

- name: Extract web-vault files into place
  become: true
  unarchive:
    src: "{{ vaultwarden_web_vault_tarball }}"
    dest: "{{ vaultwarden_state_dir }}"
    remote_src: true
    owner: "{{ vaultwarden_system_user }}"
    group: "{{ vaultwarden_system_user }}"
    mode: '750'
