---
# TODO: Add flent https://flent.org/intro.html
# TODO: Add irtt https://github.com/heistp/irtt

- name: Create directories
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: '755'
  loop:
    - path: "{{ speedtest_compose_dir }}"

- name: Add Docker compose file
  become: true
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ speedtest_compose_dir }}/docker-compose.yml"
    mode: '640'

- name: Start Speedtest
  become: true
  ansible.builtin.command:
    cmd: docker compose up -d
    chdir: "{{ speedtest_compose_dir }}"
