---
ansible_become_password: "{{ vault_ansible_become_password }}"

wireguard_server_keys: "{{ vault_wireguard_server_keys }}"

wireguard_addresses:
  - "{{ '192.168.179.0/24' | ansible.utils.ipaddr('1') }}"
wireguard_peers:
  AllanPhone:
    PublicKey: 'd1TvmSlr/N3xvQprb0wZsL/KzcyTLxlaJC8AhqgvuTQ='
    AllowedIPs: "{{ wireguard_addresses[0] | ansible.utils.ipaddr('2') | ansible.utils.ipaddr('address') }}/32"
  AllanLaptop:
    PublicKey: 'qqEetl1bfs/yUzCJeZWfAGXsQ0gt6mqzxx8oS6ayiFQ='
    AllowedIPs: "{{ wireguard_addresses[0] | ansible.utils.ipaddr('3') | ansible.utils.ipaddr('address') }}/32"
  Test:
    PublicKey: 'wRwy276OhOIYvCPSsoM9EInTvE+x+0C8Oe82wD7qmzg='
    AllowedIPs: "{{ wireguard_addresses[0] | ansible.utils.ipaddr('4') | ansible.utils.ipaddr('address') }}/32"

inadyn_period: 600
inadyn_ddns_configurations:
  provider:
    - default@duckdns.org:
        username: "{{ vault_duckdns_token }}"
        password: 'n/a'
        hostname: "{{ vault_orangepi_hostname }}"
