ARG DEBIAN_VERSION=stable
FROM debian:${DEBIAN_VERSION}-slim

RUN apt-get update \
  && apt-get install -y \
    wireguard \
    iptables \
    iproute2 \
  && rm -rf /var/lib/apt/lists/*

COPY init.sh /

EXPOSE 51820/udp

ENTRYPOINT [ "/init.sh" ]
