---
- name: Install packages
  become: true
  ansible.builtin.package:
    name:
      - sqlite            # sqlite3 on Debian
      - dovecot
      - postfix
      - opendkim          # Requires EPEL on CentOS
      - opendmarc         # Requires EPEL on CentOS
    state: present

- name: Create mailboxes folder
  become: true
  ansible.builtin.file:
    path: "{{ mail_root }}"
    state: directory

- name: Create an empty user database
  become: true
  shell: >
    echo "CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT, email TEXT NOT NULL UNIQUE, password TEXT NOT NULL, extra, privileges TEXT NOT NULL DEFAULT '');" | sqlite3 {{ db_path }};
    echo "CREATE TABLE aliases (id INTEGER PRIMARY KEY AUTOINCREMENT, source TEXT NOT NULL UNIQUE, destination TEXT NOT NULL, permitted_senders TEXT);" | sqlite3 {{ db_path }};
  args:
    creates: "{{ db_path }}"

- name: Apply configuration files
  become: true
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: dovecot.conf
      dest: /etc/dovecot/dovecot.conf
    - src: dovecot-sql.conf.ext
      dest: /etc/dovecot/conf.d/dovecot-sql.conf.ext
    - src: main.cf
      dest: /etc/postfix/main.cf

- name: Configure Postfix database queries
  become: true
  ansible.builtin.template:
    src: postfix_db_query.cf.j2
    dest: "{{ item.dest }}"
  loop:
    - dest: /etc/postfix/virtual-mailbox-domains.cf
      query: "SELECT 1 FROM users WHERE email LIKE '%%@%s' UNION SELECT 1 FROM aliases WHERE source LIKE '%%@%s'"
    - dest: /etc/postfix/virtual-mailbox-maps.cf
      query: "SELECT 1 FROM users WHERE email='%s'"
    - dest: /etc/postfix/virtual-alias-maps.cf
      query: "SELECT destination from (SELECT destination, 0 as priority FROM aliases WHERE source='%s' AND destination<>'' UNION SELECT email as destination, 1 as priority FROM users WHERE email='%s') ORDER BY priority LIMIT 1;"
