---
# community.docker.docker_compose currently does not support docker-compose >= 2.0.0
- name: Restart Pi-hole
  become: true
  ansible.builtin.command:
    cmd: docker compose down
    chdir: "{{ pihole_compose_path }}"
  notify: Start Pi-hole

- name: Start Pi-hole
  become: true
  ansible.builtin.command:
    cmd: docker compose up -d
    chdir: "{{ pihole_compose_path }}"
