---
- name: (RedHat) Install packages
  become: true
  package:
    name:
      - iptables-services
      - cronie
      - git
      - wget
      - curl
      - tar
      - less
      - sudo
      - tmux
      - nano
      - bind-utils
      - dnf-automatic
    state: present

- name: (RedHat) Limit automatic updates to security patches
  become: true
  lineinfile:
    path: /etc/dnf/automatic.conf
    regexp: '^upgrade_type ='
    line: 'upgrade_type = security'
  when: not ansible_check_mode

- name: (RedHat) Enable automatic updates
  become: true
  service:
    name: dnf-automatic-install.timer
    enabled: true
    state: started

- name: (RedHat) Create timer for automatic reboots every month (for updates that may require it)
  become: true
  copy:
    src: automatic_reboot.timer
    dest: /lib/systemd/system/automatic_reboot.timer
    mode: '644'

- name: (RedHat) Enable automatic reboots
  become: true
  service:
    daemon_reload: true
    name: automatic_reboot.timer
    enabled: true
    state: started

- name: (RedHat) Set default text editor
  lineinfile:
    path: ~/.bash_profile
    regexp: '^export EDITOR='
    line: 'export EDITOR="nano"'
