---
- block:
    - name: Restart sshd service
      become: true
      service:
        name: sshd
        state: restarted
  rescue:
    - name: Restart ssh service
      become: true
      service:
        name: ssh
        state: restarted
