---
# certbot_python_version: "{{ 'python' if ansible_python.version.major == 2 else 'python' ~ ansible_python.version.major }}"

certbot_path: /usr/local/bin/certbot-auto
certbot_auto_signature_path: /tmp/certbot-auto.asc
certbot_credentials_path: /root/certbotcredentials
certbot_deploy_hook_dir: /etc/letsencrypt/renewal-hooks/deploy
certbot_renew_cronjob: "{{ certbot_path | quote }} renew \
      --pre-hook {{ certbot_renew_hooks.pre | quote }} \
      --post-hook {{ certbot_renew_hooks.post | quote }}"
