---
- name: (RedHat) Install Docker dependencies
  ansible.builtin.yum:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present

- name: (RedHat) Add package repositories
  yum_repository:
    name: Docker
    description: Official Docker packages
    baseurl: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/{{ ansible_distribution_version }}/{{ ansible_architecture }}/stable"
    gpgcheck: true
    gpgkey: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    repo_gpgcheck: true
    enabled: true

- name: (RedHat) Install Docker
  ansible.builtin.yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
