---
linuxgsm_game: csgoserver
linuxgsm_common_config: |
  gametype="3"
  gamemode="0"
  tickrate="128"
  fn_parms(){
  parms="-game csgo -usercon -strictportbind -ip 0.0.0.0 -port ${port} +clientport ${clientport} +tv_port ${sourcetvport} +sv_setsteamaccount ${gslt} -tickrate ${tickrate} +map ${defaultmap} +servercfgfile ${servercfg} -maxplayers_override ${maxplayers} +mapgroup ${mapgroup} +game_type ${gametype} +game_mode ${gamemode} +host_workshop_collection ${wscollectionid} +workshop_start_map ${wsstartmap} -authkey ${wsapikey} -nobreakpad"
  }
linuxgsm_instance_config:  |
  gslt="{{ vault_csgo_gslt_token }}"
linuxgsm_game_config:
  path: "serverfiles/csgo/cfg/{{ linuxgsm_instancename }}.cfg"
  config: |
    hostname "Nino's Dungeon"
    rcon_password "{{ vault_csgo_rcon_password }}"
    sv_password "{{ vault_csgo_server_password }}"
    exec gamemode_competitive.cfg
    sv_region 3
    sv_pure 1
    sv_pausable 1
    sv_mincmdrate 128
    sv_minupdaterate 128
    bot_quota 2
    bot_difficulty 3
    mp_warmuptime 60
    mp_warmuptime_allplayers_connected 30
