---
wireguard_server_keys:
  private: "{{ vault_wireguard_home_keys.private }}"
  public: "{{ vault_wireguard_home_keys.public }}"
wireguard_addresses:
  - "{{ vpn_network_ipv4 | ansible.utils.ipaddr('1') }}"
wireguard_peers:
  orangepizero:
    PublicKey: 'HcqY+vyuCP00we+DWbv0GL5oeupHrhVE7GnAbDKuvn8='
    AllowedIPs: "{{ vpn_network_ipv4 | ansible.utils.ipaddr('2') | ansible.utils.ipaddr('address') }}/32"
  NinosDesktop:
    PublicKey: 'KfWraMr/u5fsN3DCG10k7fUAbDH8cInJ9aVuMq/IlTI='
    AllowedIPs: "{{ vpn_network_ipv4 | ansible.utils.ipaddr('3') | ansible.utils.ipaddr('address') }}/32"
  NinosOP8T:
    PublicKey: 'NX95oJKZjkx7GfmbkkcfFUWeULqGIRsFTGrJj8b5mjo='
    AllowedIPs: "{{ vpn_network_ipv4 | ansible.utils.ipaddr('4') | ansible.utils.ipaddr('address') }}/32"
  NinosLaptop:
    PublicKey: 'sPerTiUos9AYtwcdEbStPLz33mitT6mSR0kugC2/4Hg='
    AllowedIPs: "{{ vpn_network_ipv4 | ansible.utils.ipaddr('5') | ansible.utils.ipaddr('address') }}/32"
  NinosWorkLaptop:
    PublicKey: 'k3x6G3OTimZpwDrD2RTAa3WVd3lq2fHginyFU7MfFWk='
    AllowedIPs: "{{ vpn_network_ipv4 | ansible.utils.ipaddr('6') | ansible.utils.ipaddr('address') }}/32"

smb_backup_dir: /mnt/backup
smb_mounts:
  backup_vaultwarden:
    network_path: //harkonnen.{{ local_domain }}/ServerBackup/vaultwarden
    local_path: "{{ smb_backup_dir }}/vaultwarden"
    options: '_netdev,dir_mode=0555,file_mode=0444'
    username: "{{ vault_smb_server_backup_credentials.username }}"
    password: "{{ vault_smb_server_backup_credentials.password }}"
  backup_jellyfin:
    network_path: //harkonnen.{{ local_domain }}/ServerBackup/jellyfin
    local_path: "{{ smb_backup_dir }}/jellyfin"
    options: '_netdev,dir_mode=0555,file_mode=0444'
    username: "{{ vault_smb_server_backup_credentials.username }}"
    password: "{{ vault_smb_server_backup_credentials.password }}"
  backup_gitea:
    network_path: //harkonnen.{{ local_domain }}/ServerBackup/gitea
    local_path: "{{ smb_backup_dir }}/gitea"
    options: '_netdev,dir_mode=0555,file_mode=0444'
    username: "{{ vault_smb_server_backup_credentials.username }}"
    password: "{{ vault_smb_server_backup_credentials.password }}"
  media:
    network_path: //harkonnen.{{ local_domain }}/Media
    local_path: "/mnt/media"
    options: '_netdev,dir_mode=0555,file_mode=0444'
    username: "{{ vault_smb_jellyfin_credentials.username }}"
    password: "{{ vault_smb_jellyfin_credentials.password }}"

jellyfin_media_dir: "{{ smb_mounts.media.local_path }}"

vaultwarden_reset_admin_config: true
vaultwarden_signups_allowed: false
vaultwarden_admin_token: "{{ vault_vaultwarden.admin_token }}"
vaultwarden_domain: "https://{{ certbot_domain }}"
vaultwarden_smtp:
  host: "{{ vault_vaultwarden.smtp.host }}"
  from: "{{ vault_vaultwarden.smtp.username }}"
  credentials:
    username: "{{ vault_vaultwarden.smtp.username }}"
    password: "{{ vault_vaultwarden.smtp.password }}"

inadyn_period: 600
inadyn_ddns_configurations:
  provider:
    - default@cloudflare.com:
        username: 'n/a'
        password: "{{ vault_cloudflare.zone_key }}"
        hostname: "{{ vault_home_domain }}"
