---
wg_server_keys:
  private: "{{ vault_wg_privatekey }}"
  public: 'yVEJ55Lf2ftBarWRbtCprZO+qGLh/0UE9rmk9Er22DU='

wg_address:
  - "{{ wireguard_network_ipv4 | ansible.utils.ipaddr('1') }}"

# wg_preup:
#   - "ip route del {{ wireguard_network_ipv4 | ansible.utils.ipaddr('network/prefix') }}"
wg_postup:
  - "iptables -A INPUT -p udp --dport {{ wg_listenport }} -j ACCEPT"
  - 'iptables -A FORWARD -i %i -j ACCEPT'
  - 'iptables -A FORWARD -o %i -j ACCEPT'
wg_postdown:
  - "iptables -D INPUT -p udp --dport {{ wg_listenport }} -j ACCEPT"
  - 'iptables -D FORWARD -i %i -j ACCEPT'
  - 'iptables -D FORWARD -o %i -j ACCEPT'

## OPNsense
# Server 60, Android client 20: occasionally drops
# Server 55: works
## VyOS
# Server 55: works
wireguard_keepalive: 55
wg_peers:
  - { publickey: 'HcqY+vyuCP00we+DWbv0GL5oeupHrhVE7GnAbDKuvn8=', allowedips: '172.20.255.2/32', persistentkeepalive: "{{ wireguard_keepalive }}", comment: 'orangepizero' }
  - { publickey: 'KfWraMr/u5fsN3DCG10k7fUAbDH8cInJ9aVuMq/IlTI=', allowedips: '172.20.255.3/32', persistentkeepalive: "{{ wireguard_keepalive }}", comment: 'NiklasPC' }
  - { publickey: 'Jx6tOgG6UeZZl3TbAUscmR6wAF4eGaFZjka1g+copRU=', allowedips: '172.20.255.10/32', persistentkeepalive: "{{ wireguard_keepalive }}", comment: 'Ninos OP3' }
  - { publickey: 'vOLaI/p3YkDVTXiYmkhGo7378mJSJgQRg1qwk68lgiU=', allowedips: '172.20.255.11/32', persistentkeepalive: "{{ wireguard_keepalive }}", comment: 'Ninos OPO' }
  - { publickey: 'sPerTiUos9AYtwcdEbStPLz33mitT6mSR0kugC2/4Hg=', allowedips: '172.20.255.12/32', persistentkeepalive: "{{ wireguard_keepalive }}", comment: 'Ninos Laptop' }
  - { publickey: 'k3x6G3OTimZpwDrD2RTAa3WVd3lq2fHginyFU7MfFWk=', allowedips: '172.20.255.13/32', persistentkeepalive: "{{ wireguard_keepalive }}", comment: 'Ninos Work Laptop' }
  - { publickey: 'NX95oJKZjkx7GfmbkkcfFUWeULqGIRsFTGrJj8b5mjo=', allowedips: '172.20.255.14/32', persistentkeepalive: "{{ wireguard_keepalive }}", comment: 'Ninos OP8T' }
