---
- name: Install requirements
  ansible.builtin.package:
    name: ifenslave
    state: present

- name: Configure linux bond and WiFi credentials
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '644'
  loop:
    - { src: bond.j2, dest: /etc/network/interfaces.d/bond }
    # - { src: wpa_supplicant.j2, dest: /etc/wpa_supplicant/wpa_supplicant.conf }

- name: Add WiFi credentials
  ansible.builtin.blockinfile:
    path: "{{ bonded_interface_wpa_conf_path }}"
    state: present
    create: true
    block: |
      ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
      update_config=1
      country={{ bonded_interface_wpa_country }}

      # RETROPIE CONFIG START
      network={
              ssid="{{ bonded_interface_wpa_ssid }}"
              bssid={{ bonded_interface_wpa_bssid }}
              psk="{{ bonded_interface_wpa_pass }}"
      }
      # RETROPIE CONFIG END
  no_log: true
  when: bonded_interface_wpa_ssid is defined

- name: Disable DHCP for bonded interfaces
  ansible.builtin.lineinfile:
    path: /etc/dhcpcd.conf
    regexp: '^denyinterfaces'
    state: present
    line: "denyinterfaces {{ bonded_interfaces | join(' ') }}"

# TODO: Restart network interfaces
