---
- name: Create each instance
  ansible.builtin.include_tasks: instance.yml
  vars:
    instance_name: "{{ instance_item.0 }}"
    image_version: "{{ instance_item.1.image_version }}"
    instance_config: "{{ instance_item.1.instance_config }}"
    game_config: "{{ instance_item.1.game_config }}"
    ports: "{{ instance_item.1.ports }}"
    compose_dir: "{{ docker_compose_dir }}/linuxgsm/{{ instance_name }}"
    data_dir: "{{ compose_dir }}/data"
  loop: "{{ linuxgsm_servers.items() }}"
  loop_control:
    loop_var: instance_item
