---
bonded_interfaces: "{{ ansible_interfaces | difference(['lo','bond0']) | sort }}"
bonded_interface_primary: "{{ bonded_interfaces[0] }}"
bonded_interface_wpa_conf_path: '/etc/wpa_supplicant/wpa_supplicant.conf'

# bonded_interface_wpa_ssid:
# bonded_interface_wpa_bssid:
# bonded_interface_wpa_pass:
