---
gateway_address: '172.21.1.1'
local_network_ipv4: '172.21.1.0/24'
# local_network_ipv6: '::/0'

home_domain: niklasea.dk
local_domain: "internal.{{ home_domain }}"
dhcp_address: "{{ hosts.pihole01.ipv4_address }}"
dhcp_range:
  start: '172.21.1.50'
  end: '172.21.1.254'
dhcp_dns:
  - "{{ dhcp_address }}"
  - "{{ hosts.pihole02.ipv4_address }}"
ntp_addresses:
  - "{{ hosts.ds216j.ipv4_address }}"
  - "{{ hosts.retropie.ipv4_address }}"

ansible_become_password: "{{ vault_ansible_become_password }}"

smb_backup_folder: /mnt/backup

certbot_domain: "{{ inventory_hostname_short }}.{{ local_domain }}"
certbot_subject_alt_names:
  - "{{ inventory_hostname_short }}.{{ home_domain }}"
certbot_email: niklasea@gmail.com
certbot_use_dns: true
certbot_dns_plugin: cloudflare
certbot_dns_credentials: |
  # https://certbot-dns-cloudflare.readthedocs.io/en/stable/#credentials
  dns_{{ certbot_dns_plugin }}_email = {{ vault_cloudflare_email }}
  dns_{{ certbot_dns_plugin }}_api_key = {{ vault_cloudflare_global_api_key }}
certbot_dns_propagation: 10

wireguard_network: '172.20.255.0/25'
# openvpn_network: '172.20.255.128/25'

static_routes:
  - "{{ wireguard_network }},{{ hosts.wireguard.ipv4_address }}"
  # - "{{ openvpn_network }},{{ hosts.openvpn.ipv4_address }}"

wifi_pass: "{{ vault_wifi_pass }}"

hosts:
  ordos:
    ipv4_address: '172.21.1.2'
  arrakis:
    hardware_address: '08:BD:43:75:B3:B9'
    ipv4_address: '172.21.1.3'
  ds216j:
    hardware_address: '00:11:32:78:4F:05'
    ipv4_address: '172.21.1.4'
  retropie:
    hardware_address: 'B8:27:EB:C5:7A:DF,B8:27:EB:90:2F:8A'
    ipv4_address: '172.21.1.5'
  arvon:
    hardware_address: '98:DA:C4:63:68:D6'
    ipv4_address: '172.21.1.6'
  ninosdesktop:
    hardware_address: 'AC:22:0B:C7:D1:EA,24:0A:64:49:A6:65'
    ipv4_address: '172.21.1.9'
  unbound:
    hardware_address: 'A6:BD:E3:18:87:C4'
    ipv4_address: '172.21.1.10'
  pihole01:
    hardware_address: '26:3F:BF:92:0C:B5'
    ipv4_address: '172.21.1.11'
  pihole02:
    hardware_address: 'E6:86:C9:36:B0:66'
    ipv4_address: '172.21.1.12'
  wireguard:
    hardware_address: '76:B3:05:81:E3:FF'
    ipv4_address: '172.21.1.15'
  mail:
    ipv4_address: '172.21.1.19'
  reverse_proxy:
    ipv4_address: '172.21.1.20'
  plex:
    hardware_address: '0E:C2:86:78:4C:3A'
    ipv4_address: '172.21.1.21'
  jellyfin:
    hardware_address: '56:AE:02:B4:3B:0A'
    ipv4_address: '172.21.1.23'
  valheim:
    hardware_address: 'ca:72:fe:5f:b5:93'
    ipv4_address: '172.21.1.22'
