---
internal_network_ipv4: '172.21.1.0/24'
guest_network_ipv4: '172.21.9.0/24'

gateway_address: "{{ internal_network_ipv4 | ansible.utils.ipaddr('1') }}"

home_domain: "{{ vault_home_domain }}"
local_domain: "internal.{{ home_domain }}"
dhcp_address: "{{ gateway_address }}"
dhcp_range:
  start: "{{ internal_network_ipv4 | ansible.utils.ipaddr('50') }}"
  end: "{{ internal_network_ipv4 | ansible.utils.ipaddr('-2') }}"
dhcp_dns_addresses:
  - "{{ hosts.private.ipv4_address }}"
dhcp_ntp_addresses:
  - "{{ hosts.private.ipv4_address }}"

haproxy_docker_internal_network: '10.0.0.0/16'

ansible_become_password: "{{ vault_ansible_become_password }}"

smb_backup_dir: /mnt/backup

certbot_domain: "{{ inventory_hostname_short }}.{{ local_domain }}"
certbot_subject_alt_names:
  - "{{ inventory_hostname_short }}.{{ home_domain }}"
certbot_email: "{{ vault_notification_email }}"
certbot_use_dns: true
certbot_dns_plugin: cloudflare
certbot_dns_credentials: |
  # https://certbot-dns-cloudflare.readthedocs.io/en/stable/#credentials
  dns_{{ certbot_dns_plugin }}_email = {{ vault_cloudflare.email }}
  dns_{{ certbot_dns_plugin }}_api_key = {{ vault_cloudflare.global_api_key }}
certbot_dns_propagation: 10

wireguard_network_ipv4: '172.21.0.0/24'

wifi_pass: "{{ vault_wifi_pass }}"

hosts:
  ordos:
    ipv4_address: "{{ internal_network_ipv4 | ansible.utils.ipaddr('2') }}"
  arrakis: # Primary network switch.
    hardware_address: '08:BD:43:75:B3:B9'
    ipv4_address: "{{ internal_network_ipv4 | ansible.utils.ipaddr('3') }}"
  arvon: # WiFi access point.
    hardware_address: '98:DA:C4:63:68:D6'
    ipv4_address: "{{ internal_network_ipv4 | ansible.utils.ipaddr('6') }}"
  public: # Public server.
    ipv4_address: "{{ internal_network_ipv4 | ansible.utils.ipaddr('20') }}"
  private: # Internal server.
    ipv4_address: "{{ internal_network_ipv4 | ansible.utils.ipaddr('21') }}"
