---
- name: Generate private keys
  command: wg genkey
  register: wg_client_private_keys
  loop: "{{ range(0, wg_create_clients) }}"

- name: Generate public keys
  command: wg pubkey
  args:
    stdin: "{{ wg_client_private_keys.stdout }}"
  register: wg_client_public_keys
  loop: "{{ range(0, wg_create_clients) }}"

- name: Create client config directory
  file:
    name: /etc/wireguard/clients
    state: directory
    owner: root
    group: root
    mode: '700'
  when: wg_create_clients > 0

- name: Generate client config files
  template:
    src: wg_client.conf.j2
    dest: /etc/wireguard/clients/wg_client{{ item }}.conf
    owner: root
    group: root
    mode: '600'
  loop: "{{ range(0, wg_create_clients) | list }}"

# TODO: Output QR-codes as well?
- name: Download client configs to Ansible host
  fetch:
    src: /etc/wireguard/clients/wg_client{{ item }}.conf
    dest: "{{ wg_clientconf_directory }}"
    flat: true
    mode: '600'
  loop: "{{ range(0, wg_create_clients) | list }}"
  when: wg_clientconf_directory is defined

- name: Stop WireGuard
  service:
    name: "wg-quick@{{ wg_interface_name }}"
    state: stopped

- name: Append created peers to existing server config
  blockinfile:
    path: "/etc/wireguard/{{ wg_interface_name }}.conf"
    state: present
    block: |
      [Peer]
      PublicKey = {{ wg_client_public_keys.results[i].stdout }}
      AllowedIPs = {{ wg_network | ansible.utils.ipaddr(loopindex+1) | ansible.utils.ipaddr('host') }}
    marker: "# {mark} ANSIBLE ADDED CLIENT {{ loopindex }}"
  loop: "{{ range(0, wg_create_clients) }}"
  loop_control:
    index_var: loopindex
  notify: Restart WireGuard
