---
# TODO: How to distribute the public key if one is generated? Save in file for later?

- name: Make sure WireGuard config directory exists
  become: true
  file:
    name: /etc/wireguard
    state: directory
    owner: root
    group: root
    mode: '755'

# TODO: Try to read existing key first?
- name: Generate private key
  command: wg genkey
  register: wg_private_key
  when: wg_server_keys is not defined

- name: Generate public key
  command: wg pubkey
  args:
    stdin: "{{ wg_private_key.stdout }}"
  register: wg_public_key
  when: wg_private_key is changed

# If overwriting existing config, any old pre-/post-down rules will not run when restarting the server.
# TODO: Shut down server first if server config has changed
- name: Generate server config
  become: true
  template:
    src: wg.conf.j2
    dest: "/etc/wireguard/{{ wg_interface_name }}.conf"
    owner: root
    group: root
    mode: '600'
    backup: true
  notify: Restart WireGuard
