---
- name: Create directories
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: '755'
  loop:
    - path: "{{ wireguard_compose_dir }}"

- name: Generate server config
  become: true
  ansible.builtin.template:
    src: wg.conf.j2
    dest: "{{ wireguard_compose_dir }}/{{ wireguard_interface_name }}.conf"
    owner: "{{ docker_remap_user }}"
    group: "{{ docker_remap_user }}"
    mode: '600'
  register: _configuration_files

- name: Add Docker compose file
  become: true
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ wireguard_compose_dir }}/docker-compose.yml"
    mode: '640'

- name: Stop docker services
  become: true
  ansible.builtin.command:
    cmd: docker compose down
    chdir: "{{ wireguard_compose_dir }}"
  when: _configuration_files is changed

- name: Start WireGuard
  become: true
  ansible.builtin.command:
    cmd: docker compose up -d
    chdir: "{{ wireguard_compose_dir }}"
  register: _docker_compose_up_result
  changed_when: "'Running' not in _docker_compose_up_result.stderr"
