---
- name: Create directories
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: '755'
  loop:
    - path: "{{ wireguard_config_dir }}"

- name: Generate server config
  become: true
  template:
    src: wg.conf.j2
    dest: "{{ wireguard_config_dir }}/{{ wireguard_interface_name }}.conf"
    owner: root
    group: root
    mode: '600'
  notify: Restart WireGuard
  tags: update_config

- name: Add Docker compose file
  become: true
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ wireguard_config_dir }}/docker-compose.yml"
    mode: '640'
  notify: Restart WireGuard
  tags: update_config
