---
- name: Create lists
  become: true
  template:
    src: list.j2
    dest: "{{ pihole_config_path }}/{{ item.dest }}"
    owner: root
    group: root
    mode: '644'
  loop:
    - list: "{{ pihole_adlists }}"
      dest: adlists.list
    - list: "{{ pihole_regexlists }}"
      dest: regex.list
    - list: "{{ pihole_blacklists }}"
      dest: blacklist.txt
    - list: "{{ pihole_whitelists }}"
      dest: whitelist.txt
  loop_control:
    label: "Created list: {{ item.dest }}"
  notify: Pi-hole gravity

# TODO: Submit a pull request to pi-hole to make it possible to reload without running gravity.
- name: Apply Pi-hole configuration
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '644'
  loop:
    - { src: setupVars.conf.j2, dest: "{{ pihole_setupvarsfile }}" }
  notify: Pi-hole repair

# TODO: Add split DNS configuration.
- name: Apply Pi-hole configuration
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '644'
  loop:
    # - { src: setupVars.j2, dest: "{{ pihole_setupvarsfile }}" }
    - { src: pihole-FTL.conf.j2, dest: "{{ pihole_config_path }}/pihole-FTL.conf" }
    - { src: dnsmasq.conf.j2, dest: "{{ pihole_dnsmasq_config_path }}/pihole-ansible.conf" }
    - { src: dhcp_reservations.conf.j2, dest: "{{ pihole_dnsmasq_config_path }}/04-pihole-static-dhcp.conf" }
  notify: Pi-hole reload
