---
# Pi-hole on Debian Proxmox containers depends on resolvconf which might override DNS settings.
# To avoid losing DNS during the install, install resolvconf first.
# TODO: Fix on systems that do not use resolv.conf by default (e.g. Ubuntu 18.04)

- name: (Debian) Install resolvconf
  package:
    name: resolvconf
    state: present
  register: pihole_resolvconf

- block:
    - name: (Debian) Backup resolv.conf
      copy:
        src: /etc/resolv.conf
        dest: /etc/resolv.conf.bck
        remote_src: true

    - name: (Debian) Restart resolvconf service
      service:
        name: resolvconf
        state: restarted

    - name: (Debian) Restore resolv.conf
      command: mv /etc/resolv.conf.bck /etc/resolv.conf
      args:
        removes: /etc/resolv.conf.bck
  when: pihole_resolvconf is changed
