---
# Pi-hole currently lacks a way to directly reload settings from /etc/pihole/setupVars.conf
# Instead we set DHCP and conditional forwarding settings manually
# TODO: No longer works
# TODO: This currently breaks the WPAD fix implemented in Pi-hole, running pihole -r fixes it
# TODO: Submit pull request with a reload function
- name: Enable DHCP
  become: true
  command: >
    pihole -a enabledhcp {{ pihole_dhcp_range.start | quote }} {{ pihole_dhcp_range.end | quote }} {{ pihole_gateway_address | quote }}
    {{ pihole_dhcp_leasetime | quote }} {{ pihole_domain | quote }} {{ pihole_dhcp_ipv6 | quote }} {{ pihole_dhcp_rapid_commit | quote }}
  when: pihole_dhcp == 'true'

- name: Disable DHCP
  become: true
  command: pihole -a disabledhcp
  when: pihole_dhcp == 'false'

- name: Enable conditional forwarding
  become: true
  command: >
    pihole -a setdns {{ pihole_upstream_dns | join(',') | quote }} {{ 'domain-needed' if pihole_dns_fqdn_required == 'true' else 'domain-not-needed' }}
    {{ 'bogus-priv' if pihole_dns_bogus_priv == 'true' else 'no-bogus-priv' }} {{ 'dnssec' if pihole_dnssec == 'true' else 'no-dnssec' }}
    conditional_forwarding
    {{ pihole_conditional_fwd_rules[0].server_ip | quote }}
    {{ pihole_conditional_fwd_rules[0].domain | quote }}
    {{ pihole_conditional_fwd_rules[0].server_ip.split('.')[0:3] | reverse | list | join('.') | quote }}.in-addr.arpa
  when: pihole_conditional_fwd == 'true'

- name: Disable conditional forwarding
  become: true
  command: >
    pihole -a setdns {{ pihole_upstream_dns | join(',') | quote }} {{ 'domain-needed' if pihole_dns_fqdn_required == 'true' else 'domain-not-needed' }}
    {{ 'bogus-priv' if pihole_dns_bogus_priv == 'true' else 'no-bogus-priv' }} {{ 'dnssec' if pihole_dnssec == 'true' else 'no-dnssec' }}
  when: pihole_conditional_fwd == 'false'
