---
unbound_git_repo: https://github.com/NLnetLabs/unbound.git
unbound_src_dir: "{{ unbound_install_dir }}/src/unbound/{{ unbound_release }}"
unbound_install_dir: /usr/local
unbound_conf_dir: /etc/unbound
unbound_conf_file: "{{ unbound_conf_dir }}/unbound.conf"
unbound_state_dir: /var/lib/unbound
unbound_root_certificate: "{{ unbound_state_dir }}/icannbundle.pem"
unbound_root_certificate_url: http://data.iana.org/root-anchors/icannbundle.pem
unbound_root_hints_file: "{{ unbound_state_dir }}/root.hints"
unbound_root_hints_url: https://www.internic.net/domain/named.cache
unbound_root_key_path: "{{ unbound_state_dir }}/root.key"
# Not /run/unbound because SELinux...
unbound_pidfile_dir: /run/unbound_custom
unbound_user: unbound

# When using --with-conf-file, Unbound working directory defaults to --with-conf-file parent dir
# PID file is created before dropping privileges, can be created outside chroot
# chroot disabled in favour of systemd service hardening because it complicates access to entropy and config files
# Uses with-libevent to support outgoing-range > 1024
# Hardening with PIE, RELRO and NOW
# Enables EDNS Client Subnet and TCP Fast Open
unbound_build_flags: >
  --prefix={{ unbound_install_dir }}
  --with-run-dir={{ unbound_state_dir }}
  --with-conf-file={{ unbound_conf_file }}
  --with-chroot-dir=""
  --with-pidfile={{ unbound_pidfile_dir }}/unbound.pid
  --with-username={{ unbound_user }}
  --with-libevent
  --enable-pie
  --enable-relro-now
  --enable-subnet
  --enable-cachedb
  --enable-tfo-client
  --enable-tfo-server

unbound_base_config: |
  server:
      # Enable or disable whether the unbound server forks into the
      # background as a daemon. Set the value to no when unbound runs
      # as systemd service.
      do-daemonize: no
      # DNSSEC trust anchor
      auto-trust-anchor-file: {{ unbound_root_key_path }}
      root-hints: {{ unbound_root_hints_file }}

  remote-control:
      # Enable remote control with unbound-control(8)
      control-enable: yes
